version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_test
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:latest
    container_name: redis_test
    restart: always
    ports:
      - "6379:6379"
  mongodb:
    image: mongo:latest
    container_name: mongo_test
    restart: always
    ports:
      - "27017:27017"